create table UnidadMedida (IdUM int identity(1,1), Nombre nvarchar(50) not null, Descripcion nvarchar(255), constraint PK_UnidadMedida primary key (IdUM), constraint UQ_UnidadMedida_Nombre unique (Nombre));
create table Producto (CodProducto int identity(1,1), Descripcion nvarchar(255) not null, constraint PK_Producto primary key (CodProducto));
create table EstadoOE (IdEstadoOE int identity(1,1), Nombre varchar(8) not null, constraint PK_EstadoOE primary key (IdEstadoOE), constraint UQ_EstadoOE_Nombre unique (Nombre), constraint CK_EstadoOE_Nombre check (Nombre in ('Proceso', 'Enviado', 'Recibido')));
create table Usuario (IdUsuario int identity(1,1), Clave nvarchar(100) not null, Nombre nvarchar(50) not null, Apellido nvarchar(50), Email nvarchar(254) not null, FechaAlta datetime not null default getdate(), constraint PK_Usuario primary key (IdUsuario), constraint UQ_Usuario_Email unique (Email), constraint CK_Usuario_Email check (Email like '_%@_%._%'));
create table Sector (IdSector int identity(1,1), Nombre nvarchar(100) not null, constraint PK_Sector primary key (IdSector), constraint UQ_Sector_Nombre unique (Nombre));
create table Deposito (IdDeposito int identity(1,1), Nombre nvarchar(100) not null, Descripcion nvarchar(255), IdSector int not null, constraint PK_Deposito primary key (IdDeposito), constraint UQ_Deposito_Nombre unique (Nombre), constraint PK_Deposito_Sector foreign key (IdSector) references Sector(IdSector));
create table MovimientoStock (IdMovimiento int identity(1,1), CodProducto int not null, IdDeposito int not null, IdUM int not null, FechaVencimiento datetime not null, FechaMovimiento datetime not null default getdate(), TipoMovimiento varchar(7) not null, CantidadModificada decimal(15,2) not null, constraint PK_MovimientoStock primary key (IdMovimiento), constraint FK_MovimientoStock_Producto foreign key (CodProducto) references Producto(CodProducto), constraint FK_MovimientoStock_Deposito foreign key (IdDeposito) references Deposito(IdDeposito), constraint FK_MovimientoStock_UnidadMedida foreign key (IdUM) references UnidadMedida(IdUM), constraint CK_MovimientoStock_TipoMovimiento check (TipoMovimiento in ('Ingreso', 'Egreso', 'Espera')));
create table OrdenEntrega (NroEntrega int identity(1,1), SectorSolicita int not null, SectorProvee int not null, DepositoSolicita int not null, DepositoProvee int, UsuarioAlta int not null, UsuarioRecepcion int, IdEstadoOE int not null, FechaAlta datetime not null default getdate(), FechaRecepcion datetime, EsAnulado bit not null default 0, constraint PK_OrdenEntrega primary key (NroEntrega), constraint FK_OrdenEntrega_Sector_Solicita foreign key (SectorSolicita) references Sector(IdSector), constraint FK_OrdenEntrega_Sector_Provee foreign key (SectorProvee) references Sector(IdSector), constraint FK_OrdenEntrega_Deposito_Solicita foreign key (DepositoSolicita) references Deposito(IdDeposito), constraint FK_OrdenEntrega_Deposito_Provee foreign key (DepositoProvee) references Deposito(IdDeposito), constraint FK_OrdenEntrega_Usuario_Alta foreign key (UsuarioAlta) references Usuario(IdUsuario), constraint FK_OrdenEntrega_Usuario_Recepcion foreign key (UsuarioRecepcion) references Usuario(IdUsuario), constraint FK_OrdenEntrega_EstadoOE foreign key (IdEstadoOE) references EstadoOE(IdEstadoOE), constraint CK_OrdenEntrega_FechaRecepcion check (FechaRecepcion is null or FechaRecepcion >= FechaAlta));
create table MovimientoEntrega (IdMovimiento int, NroEntrega int, constraint PK_MovimientoEntrega primary key (IdMovimiento, NroEntrega), constraint FK_MovimientoEntrega_MovimientoStock foreign key (IdMovimiento) references MovimientoStock(IdMovimiento), constraint FK_MovimientoEntrega_OrdenEntrega foreign key (NroEntrega) references OrdenEntrega(NroEntrega));
create table EstadoOR(IdEstadoOR int identity(1,1),Nombre varchar(10) not null,constraint PK_EstadoOR primary key (IdEstadoOR),constraint UQ_EstadoOR_Nombre unique (Nombre),constraint CK_EstadoOR_Nombre check (Nombre in ('Proceso','Solicitado','Cerrado')));
create table OrdenReposicion(NroReposicion int identity(1,1),IdEstadoOR int not null,EsAnulado bit not null default 0,constraint PK_OrdenReposicion primary key (NroReposicion),constraint FK_OrdenReposicion_EstadoOR foreign key (IdEstadoOR) references EstadoOR(IdEstadoOR));
create table OrdenReposicionDetalle(NroReposicion int,CodProducto int,IdUM int not null,Cantidad decimal(15,2),constraint PK_OrdenReposicionDetalle primary key (NroReposicion,CodProducto),constraint FK_OrdenReposicionDetalle_OrdenReposicion foreign key (NroReposicion) references OrdenReposicion(NroReposicion),constraint FK_OrdenReposicionDetalle_Producto foreign key (CodProducto) references Producto(CodProducto),constraint FK_OrdenReposicionDetalle_UnidadMedida foreign key (IdUM) references UnidadMedida(IdUM),constraint CK_OrdenReposicionDetalle_Cantidad check (Cantidad>=0));
create table TipoPallet(IdTipoPallet int identity(1,1),IdUM int not null,Nombre nvarchar(50) not null,Capacidad int,constraint PK_TipoPallet primary key (IdTipoPallet),constraint FK_TipoPallet_UnidadMedida foreign key (IdUM) references UnidadMedida(IdUM),constraint UQ_TipoPallet_Nombre unique (Nombre),constraint CK_TipoPallet_Capacidad check (Capacidad>0));
create table Pallet(IdPallet int identity(1,1),IdTipoPallet int not null,CantidadDisponible int,constraint PK_Pallet primary key (IdPallet),constraint FK_Pallet_TipoPallet foreign key (IdTipoPallet) references TipoPallet(IdTipoPallet),constraint CK_Pallet_CantidadDisponible check (CantidadDisponible>=0));
create table MovimientoPallet(IdMovimiento int,IdPallet int,constraint PK_MovimientoPallet primary key (IdMovimiento,IdPallet),constraint FK_MovimientoPallet_MovimientoStock foreign key (IdMovimiento) references MovimientoStock(IdMovimiento),constraint FK_MovimientoPallet_Pallet foreign key (IdPallet) references Pallet(IdPallet));

